### ISSUE TITLE
Instabilities in evaluation of derived variable o server

### ISSUE THREAD

**Issue by miranov25** [miranov25/RootInteractive#174]
Looks like not all cases for derived variables covered. We should extend unit tests. Not clear why it happens as similar use cases we have in the test.
In example below visualization fail in case ratio '(sigmaPFitRange0/p)'
The problem was localized finding way around. 
Derived variable is calculated in case  arguments are loaded (e.g by creating them as widgets)
  
## Figure layout
```
figureArray = [
    [['logRange'], ['(sigmaPFitRange0/p)'], {"colorZvar":"colorZ"}],
    [['logRange'], ['sigmaPFitRange1'], {"colorZvar":"colorZ"}],
    [['logRange'], ['ptResolAr05T'], {"colorZvar":"colorZ"}],
    [['logRange'], ['(sigmaPFitRange0)/ptResolAr05T'], {"colorZvar":"colorZ"}],
    [['logRange'], ['(sigmaPFitRange1)/ptResolAr05T'], {"colorZvar":"colorZ"}],
    [['logRange'], ['ptResolAr05T/ptResolAr05T'], {"colorZvar":"colorZ"}],
    ['table'],
    {"size": "markerSize"}
]
```
## Table layout
```
Index(['A', 'Z', 'mass', 'dEdxAleph', 'logpScaled', 'range', 'rangeCm',
       'rangeSigmaCm', 'logRange', 'logP', 'logPFit', 'p', 'logpScaled',
       'logpScaledFit1', 'logpScaledFit0', 'logpScaledFit', 'sigmaPFitRange0',
       'sigmaPFitRange1', 'ptResolAr05T'],
      dtype='object')
```

## Error message
```
ERROR:root:Variable can not be evaluated_sigmaPFitRange0_Divide_p_
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/scope.py", line 188, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'sigmaPFitRange0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/computation/scope.py", line 199, in resolve
    return self.temps[key]
KeyError: 'sigmaPFitRange0'
ERROR:root:Variable can not be evaluated_sigmaPFitRange0_Divide_p_
```

**Comment by miranov25** [comment]
## Are tooltips parsed - to extract variables ?
Looks like modification in  pull request #175  did not fix the problem completelly.
There is similar problem occuring in case varaible is only in the hints:

Example:
* this is  faling on client  - with message - event column dosenot exist
```tooltips = [("event","@event"),("row","@row"),("sector","@sector")]```
*  this fixe the problem
```tooltips = [("row","@row"),("sector","@sector")]```
* problem could be fixed also by adding "event" column to widgets

Looks like tooltips are not parsed - to be checked
