### ISSUE TITLE
failure in makePdfMaps in case of empty slices

### ISSUE THREAD

**Issue by miranov25** [miranov25/RootInteractive#37]
## Posting bug report from JIRA - https://alice.its.cern.ch/jira/browse/ATO-495

> Hello Marian Ivanov,

> 
> I would like to do multi-dimensional fits of the ML validation data, e.g. diff(Predicted-Calculated):r:z:meanSC. Here I would like to use the makePdfMaps function from RootInteractive.
> 
> Be design, for the additional variables, like meanSC, meanDist, flucDist, derivativeDist, there will be empty bins in some of the voxels when histograming the full volume of the TPC. I think that's why I get a crash like this:
> 

```
Traceback (most recent call last):
  File "/lustre/alice/users/hellbaer/TPCwithDNN/tpcwithdnn/analyser.py", line 159, in <module>
    makeNDFits()
  File "/lustre/alice/users/hellbaer/TPCwithDNN/tpcwithdnn/analyser.py", line 69, in makeNDFits
    dfNDfits = makePdfMaps(histoND, slices, dimI)
  File "/lustre/alice/users/hellbaer/python/venv3/lib/python3.6/site-packages/RootInteractive/Tools/makePDFMaps.py", line 92, in makePdfMaps
    means.append(np.average(centerI, weights=iHisto))
  File "<__array_function__ internals>", line 6, in average
  File "/lustre/alice/users/hellbaer/python/venv3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 420, in average
    "Weights sum to zero, can't be normalized")
ZeroDivisionError: Weights sum to zero, can't be normalized
When bins have no entries, the weights iHisto will all be zero.
````

> Now, is there a quick workaround for this, e.g. skip the statistics calculation for the empty bins and mask them in the data frame? Otherwise I will have to manually select regions in the TPC.
> 
> Cheers,
> Ernst

**Comment by ehellbar** [comment]
Hello,
thank you for addressing this issue.

Here is a code snippet which should reproduce the issue:
```
import math

from RootInteractive.InteractiveDrawing.bokeh.bokehDrawSA import *
from RootInteractive.Tools.makePDFMaps import *
from root_pandas import to_root, read_root

# variables from dnnoptimiser
dirval = "/lustre/alice/users/hellbaer/NOTESData/JIRA/ATO-495/validation"
suffix = "phi90_r17_z17_filter4_poo0_drop0.00_depth4_batch0_scaler0_useSCMean1_useSCFluc1_pred_doR1_dophi0_doz0"
grid_phi = 90
grid_r = 17
grid_z = 17

def makeNDFits():

    dist_names = np.array(['DistR', 'DistRPhi', 'DistZ'])

    df = read_root(dirval + "/outputND_" + suffix + ".root", key='validation')

    # for indexDist in range(dim_output):
    indexDist = 0
    df['fluc' + dist_names[indexDist] + '_Pred-fluc' + dist_names[indexDist]] = \
        df['fluc' + dist_names[indexDist] + '_Pred'] - df['fluc' + dist_names[indexDist]]

    # (phi, r, z, meanSC)
    histoString = "fluc" + dist_names[indexDist] + "_Pred-fluc" + dist_names[indexDist] + \
                  ":phi:r:z:meanSC" + \
                  ":#r>0" + \
                  ">>histoNDmeanSC(100,-1.5,1.5," + str(grid_phi) + ",0," + str("{:.3f}".format(2*math.pi)) + "," + str(grid_r) + ",83.5,254.5," + str(grid_z) + ",0,250,40,0,1.4)"
    print("Create ND output: " + histoString)
    histoND = makeHistogram(df, histoString)
    dimI = 0
    slices = ((0, 100, 1, 0),
              (0, grid_phi, 1, 0),
              (0, grid_r, 1, 0),
              (0, grid_z, 1, 0),
              (0, 40, 1, 0))
    dfNDfits = makePdfMaps(histoND, slices, dimI)

```
Cheers,
Ernst

**Comment by ehellbar** [comment]
Hello,
the example histogram with empty bins can be found here:
/lustre/alice/users/hellbaer/NOTESData/JIRA/ATO-495/validation/histogramND_phi-r-z-meanSC.*
Cheers,
Ernst

**Comment by miranov25** [comment]
Probelm should be fixed with pull request:
https://github.com/miranov25/RootInteractive/pull/40

New issue created - speeding up of the makePdfMaps
